version: "3"

services:
  server:
    image: gitea/gitea:1.22.6
    container_name: gitea
    restart: always
    volumes:
      - gitea-data:/data
    ports:
      - "33333:3000"
      - "2222:22"

volumes:
  gitea-data: